set encoding=utf-8

set packpath=$XDG_CONFIG_HOME/vim,$VIM,$VIMRUNTIME

set undodir=$XDG_CACHE_HOME/vim/undo
set directory=$XDG_CACHE_HOME/vim/swap
set backupdir=$XDG_CACHE_HOME/vim/backup

syntax on
set number

set laststatus=2
set tabstop=2
set shiftwidth=2
set expandtab

set viminfo=
set listchars=tab:›–,trail:·,space:·
set list

set incsearch
set noshowmode
set hidden

